### PR TITLE
Group cities

### LINKED ISSUE #262: Group cities under country / continent for the navbar
For the moment it's hard-coded in the view, cf https://github.com/lewagon/www/pull/261

screen shot 2016-07-03 at 12 52 02

### LINKED ISSUE #267: Group cities by continent on Apply form
Dependency on #262 

screen shot 2016-07-07 at 12 43 25

### PR DESCRIPTION
**Pull request by Eschults**
ping @ssaunier 
fixes #267 
fixes #262 
capture d ecran 2016-09-06 a 16 06 36
capture d ecran 2016-09-06 a 16 06 40
capture d ecran 2016-09-06 a 16 06 44
capture d ecran 2016-09-06 a 16 10 22

### CODE REVIEW

**Comment by ssaunier** [comment]
🐛 Petit soucis avec le format de date affiché quand on sélectionne une autre ville :

screen shot 2016-09-06 at 21 38 42

**Comment by ssaunier** [comment]
In the previous version (still live at [lewagon.com/apply](https://www.lewagon.com/apply)), the cities were ordered by ascending starting date of next batch still available (right now Amsterdam is first as Amsterdam is the next city to start a bootcamp on Sept 26th). 

Could we keep that in city groups as well?

ping @Papillard to `pull` and `checkout` this branch locally to try the UX of the apply form. LGTM but would like your opinion as you requested the feature in the first place ;)

The API supporting city groups has been already deployed to production.

**Comment by ssaunier** [comment]
✋ Last blocking bug, the `rake` is still not passing on this branch, event with the deployed API. Need to investigate.

**Comment by Eschults** [comment]
thx @ssaunier 
fixed dates and cities order with a small patch, maybe this needs some refacto to build `@applicable_cities` as a `city_groups` hash in the first place, tell me if it's important enough to do it now, in the meantime I'll keep going through the waffle ;)

As for the Travis failures, yesterday they came from a RestClient 404 trying to get `/city_groups`, today I get `Capybara::ElementNotFound: Unable to find css "#apply"`, which means that somehow the  `ApplyForm` component couldn't be built I guess...?

**Comment by ssaunier** [comment]
@Eschults it's failing because the `ApplyForm` component in the `applies/new.html.erb` is not prerendered anymore (see line 33, `prerender: false`)

I want it prerender, because I want people to actually be able to submit the apple form event with JS disabled. So please turn that to `true` and make sure the form works with JavaScript disabled!

Thanks!

**Comment by Eschults** [comment]
thx @ssaunier 
Travis is green :)

**Comment by ssaunier** [comment]
:+1:

**Pull request merged**
