### PR TITLE
[READY] changed outdated technos

### PR DESCRIPTION
**Pull request by alex-felix**
and gemfile cleanup sorry

### CODE REVIEW

**Comment by ssaunier** [comment]
I'm not sure alphabetical order is the best for the Gemfile. I like to make groups based on feature delivered by the gem. Usually the core rails stuff (rails, jquery, puma, etc.) at the top, then stuff enhancing Rails (Sidekiq, etc..) then Assets stuff then Development/Test groups. Does it make sense? I know it's a general idea and not 100% implemented every time but that's the idea I'd like to keep.

**Comment by ssaunier** [comment]
As a follow up, order do matter, as the `Bundle.require` will load in that order:

https://stackoverflow.com/a/16725346/197944

**Comment by alex-felix** [comment]
yes gems should be in groups but the groups should be in order alphabetically 😉 

the order would only be an issue if the gems uses explicit require of other gem which I would find surprising... but I guess you never know...

**Comment by alex-felix** [comment]
removed gem `builder` and `responders` as I suspect they are not used anymore

https://github.com/plataformatec/responders
https://github.com/jimweirich/builder

ordered gems in groups in order and updated autoprefixer to suppress the gradient warning

**Comment by alex-felix** [comment]
@ssaunier close if you want 👍 

screen shot 2017-08-06 at 12 28 33

**Comment by ssaunier** [comment]
Perfect 👏  !

**Pull request merged**
